# theta — OCI E2.1.Micro AMD x86_64 (2 vCPU / 1 GB RAM / 50 GB boot, WAN 40.233.87.229)
# NixOS-infect custom configuration, 2026-07-09
# Modeled on beta (pbeta = 40.233.122.47) — same OCI image family.
#
# Used as /etc/nixos/oracle-override.nix during nixos-infect.
# nixos-infect generates configuration.nix + hardware-configuration.nix automatically;
# this file is imported alongside them via oracle-override.nix → oracle-cloud.nix chain.
#
# Operator grant (2026-07-09):
# "nixos-infect ptheta ssh alias config of theta via root using a custom theta
#  configuration.nix similar to alpha and beta
#  https://github.com/elitak/nixos-infect
#  do not use stock config.nix thats what bricked this machine from ssh access last time"

# ── /etc/nixos/configuration.nix (auto-generated by nixos-infect, kept as-is) ──
# { ... }: {
#   imports = [ ./oracle-override.nix ./hardware-configuration.nix ];
#   services.logrotate.checkConfig = false;
#   boot.tmp.cleanOnBoot = true;
#   zramSwap.enable = true;
#   networking.hostName = "theta";
#   networking.domain = "nixify.dev";
#   services.openssh.enable = true;
#   users.users.root.openssh.authorizedKeys.keys = [ "<all 4 keys>" ];
#   system.stateVersion = "25.05";
# }

# ── /etc/nixos/hardware-configuration.nix (auto-generated by nixos-infect) ──
# { modulesPath, ... }: {
#   imports = [ ./oracle-override.nix (modulesPath + "/profiles/qemu-guest.nix") ];
#   boot.loader = {
#     efi.efiSysMountPoint = "/boot/efi";
#     grub = { efiSupport = true; efiInstallAsRemovable = true; device = "nodev"; };
#   };
#   fileSystems."/boot/efi" = { device = "/dev/disk/by-uuid/7A33-0B65"; fsType = "vfat"; };
#   boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "xen_blkfront" "vmw_pvscsi" ];
#   boot.initrd.kernelModules = [ "nvme" ];
#   fileSystems."/" = { device = "/dev/sda1"; fsType = "ext4"; };
# }

# ── /etc/nixos/oracle-cloud.nix (shared OCI module, same as beta) ──
# { config, lib, pkgs, ... }:
# with lib;
# let cfg = config.services.oracle-cloud; in {
#   options.services.oracle-cloud = {
#     enable = mkEnableOption "Oracle Cloud Infrastructure integration";
#     emergencySSHKeys = mkOption { type = types.listOf types.str; default = []; };
#   };
#   config = mkIf cfg.enable {
#     services.openssh = {
#       enable = true;
#       settings = { PermitRootLogin = mkForce "prohibit-password"; PasswordAuthentication = mkForce false; };
#       openFirewall = true;
#     };
#     networking.firewall = { enable = true; allowedTCPPorts = [ 22 ]; };
#     users.users.root.openssh.authorizedKeys.keys = cfg.emergencySSHKeys;
#     boot.kernelParams = [ "console=tty1" "console=ttyS0,115200" "nvme_core.io_timeout=4294967295" ];
#     systemd.services.sshd = { after = [ "network-online.target" ]; wants = [ "network-online.target" ]; };
#     networking.useDHCP = lib.mkDefault true;
#     systemd.network.enable = mkForce false;
#     environment.systemPackages = with pkgs; [ vim htop curl git ];
#     time.timeZone = "UTC";
#     services.timesyncd.enable = true;
#   };
# }

# ── /etc/nixos/oracle-override.nix  ← THIS IS THE CRITICAL CUSTOM FILE ──
{ config, pkgs, lib, ... }:
{
  imports = [ ./oracle-cloud.nix ];

  services.oracle-cloud = {
    enable = true;
    emergencySSHKeys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAitSzTpub1baCfA94ja3DNZpxd74kDSZ8RMLDwOZEOw"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILaDf9eWQpCOZfmuCwkc0kOH6ZerU7tprDlFTc+RHxCq"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPL6GOQ1zpvnxJK0Mz+vUHgEd0f/sDB0q3pa38yHHEsC"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH29BMQNo3O6KvvuquVcmCt2gF7bhD0EPvZyUD47G+3R"
    ];
  };

  # --- Groups ---
  users.groups.nixbuilder = {};
  users.groups.ryzengrind = {};

  # Root user — no forced-command restriction post-NixOS
  users.users.root = {
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAitSzTpub1baCfA94ja3DNZpxd74kDSZ8RMLDwOZEOw"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILaDf9eWQpCOZfmuCwkc0kOH6ZerU7tprDlFTc+RHxCq"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPL6GOQ1zpvnxJK0Mz+vUHgEd0f/sDB0q3pa38yHHEsC"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH29BMQNo3O6KvvuquVcmCt2gF7bhD0EPvZyUD47G+3R"
    ];
  };

  # ryzengrind — operator user, wheel, NOPASSWD
  users.users.ryzengrind = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAitSzTpub1baCfA94ja3DNZpxd74kDSZ8RMLDwOZEOw"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILaDf9eWQpCOZfmuCwkc0kOH6ZerU7tprDlFTc+RHxCq"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPL6GOQ1zpvnxJK0Mz+vUHgEd0f/sDB0q3pa38yHHEsC"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH29BMQNo3O6KvvuquVcmCt2gF7bhD0EPvZyUD47G+3R"
    ];
  };

  # nixbuilder — remote Nix builder user
  users.users.nixbuilder = {
    isNormalUser = true;
    group = "nixbuilder";
    extraGroups = [ "wheel" ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH29BMQNo3O6KvvuquVcmCt2gF7bhD0EPvZyUD47G+3R"
    ];
  };

  # Passwordless sudo for wheel
  security.sudo.wheelNeedsPassword = lib.mkForce false;

  networking = {
    useDHCP = true;
    interfaces = {};
  };

  # Flakes + nix-command
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Extra packages (oracle-cloud.nix already adds vim htop curl git)
  environment.systemPackages = with pkgs; [
    tailscale
    git
    vim
    htop
    curl
  ];

  # Tailscale — install only; enrollment left to operator (needs authkey)
  services.tailscale.enable = true;

  system.stateVersion = lib.mkForce "25.05";
}
